name: Lint

on: push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Run BiomeJS
      run: npm run lint
    # - uses: mongolyy/reviewdog-action-biome@v1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     reporter: gitea-pr-review
    #     filter_mode: diff_context
    #     fail_on_error: true
